# Generated by Django 4.2.1 on 2023-06-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onlinecourse", "0002_auto_20230530_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_mark",
            field=models.IntegerField(default=1),
        ),
    ]
